### ISSUE TITLE
Release gem version 0.2.3 as non-platform specific version

### ISSUE THREAD

**Issue by jnbt** [glucode/flow_client#6]
Hi @nduplessis,

any chances that you release the new version of the gem (0.2.3), which includes a bug-fix for the loading the transactions, as non-platform specific gem?

I saw that you already reverted the platform restriction in 5f9b1d2, but on Rubygems the version 0.2.3 is still limited to "arm64-darwin-21".

**Comment by nduplessis** [comment]
I can look at that for you a little later today

**Comment by nduplessis** [comment]
@jnbt not entirely sure what happened with the previous gem release as rubygems.org showed that there was a 0.2.3 release that coincided with the code changes. I've however just pushed the 0.2.3 release again.

Please let me know if this is not working for you

**Comment by jnbt** [comment]
Thanks for the release. I was able to update to 0.2.3 on my Intel Mac and on another Linux machine.

I think what happend: In 7b086ba6b320676218eedb400c2f94ae43e75e65 the gemspec was set to:

```
spec.platform = Gem::Platform::CURRENT
```

This resulted in a restricted (specific) platform when the gem was released.

Thanks for the re-release. For my everything is fine now.

**Comment by nduplessis** [comment]
Yeah I just saw that as well.

Thanks for confirming that it's working
